owner: gbifatlas
repo: status

sites:
  - name: GBIF Portugal
    url: https://www.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/gbifpt92_1.png
  - name: Data - GBIF Portugal
    url: https://dados.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/gbifpt92_1.png
  - name: Toolkit - GBIF Spain
    url: https://toolkit.gbif.es/

status-website:
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GBIF Iberian service status
  introTitle: "Global Biodiversity Information Facility - Iberian Peninsula"
  introMessage: Live status page of GBIF Iberian services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

