owner: gbifatlas
repo: status

sites:
  - name: GBIF Portugal
    url: https://www.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/GBIFPORTUGAL-01.png
  - name: Data - GBIF Portugal
    url: https://dados.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/GBIFPORTUGAL-01.png
  - name: Regions - GBIF Portugal
    url: https://regioes.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/GBIFPORTUGAL-01.png
  - name: Metadata - GBIF Portugal
    url: https://metadados.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/GBIFPORTUGAL-01.png
  - name: Images - GBIF Portugal
    url: https://imagens.gbif.pt/
    icon: https://www.gbif.pt/sites/all/themes/gbifBootstrap-1.0/gbifBootstrap/images/GBIFPORTUGAL-01.png

  - name: GBIF Spain
    url: https://www.gbif.es/
    icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
  - name: Data - GBIF Spain
    url: https://datos.gbif.es/
    icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
  - name: IPT - GBIF Spain
    url: https://ipt.gbif.es/
    icon: https://ipt.gbif.es/images/gbif-logo-L.svg
  - name: eLearning - GBIF Spain
    url: https://elearning.gbif.es/
    icon: https://elearning.gbif.es/web/css/themes/GBIF/images/header-logo.png
  - name: Records - GBIF Spain
    url: https://registros.gbif.es/
    icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://images.ctfassets.net/uo17ejk9rkwj/5s7MN9pIKVTulGxIeZio8H/0836922c7764c7ff751d5ae777e16286/GBIF-2015-full-stacked.svg
  name: GBIF Iberian service status
  introTitle: "Global Biodiversity Information Facility - Iberian Peninsula"
  introMessage: Live status page of GBIF Iberian services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

